
name: Run FAANG Script on Push

on:
  push:
    branches:
      - main  # to test

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas matplotlib

    - name: Run FAANG script
      run: python faang.py

